services:
  frontend:
    build:
      context: ./src/frontend/
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: ./src/frontend/
        target: /app
      - type: volume
        target: /app/cache/
    env_file:
        - docker.env
      #   target: /app/node_modules
    # networks:
    #   - front_network

  backend:
    build:
      context: ./src/backend/
      dockerfile: Dockerfile.dev
    command: npm run start:dev
    env_file:
      - docker.env
    ports:
      - 3001:3000
    volumes:
      - type: bind
        source: ./src/backend/
        target: /app
    # networks:
    #   - db_network
    #   - back_network

  db:
    image: postgres:13
    env_file:
        - docker.env
    volumes:
      - type: volume
        source: dbtest
        target: /app/db
    expose:
      - 5432
    # networks:
    #   - db_network

  adminer:
    image: adminer
    restart: always
    environment:
      - ADMINER_DEFAULT_SERVER=db:5432
    ports:
      - 3002:8080
    # networks:
    #   - db_network
# networks:
#   db_network: {}
#   front_network: {}
#   back_network: {}


volumes:
  dbtest:
